version: '3'

services:
  web:
    build: ./docker-static/
#   build: ./docker-uptodate/
    ports:
      - "8000:8000"
      - "25500-25600"
    volumes: 
      - ./docker/minecraft_servers:/minecraft_servers
      - ./docker/db:/crafty_db
      - ./docker/backups:/crafty-web/backups
