apiVersion: v1
kind: Service
metadata:
  namespace: default
  annotations:
  labels:
    app: minecraft-crafty
  name: minecraft-crafty
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.14.6
  ports:
  - name: "minecraft-crafty"
    port: 25565
    targetPort: 25565
  - name: "crafty"
    port: 8000
    targetPort: 8000
  selector:
    app: minecraft-crafty
status:
  loadBalancer: {}
