apiVersion: v1
kind: Service
metadata:
  namespace: default
  annotations:
  labels:
    app: minecraft-crafty
  name: minecraft-crafty
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.14.6
  ports:
  - name: "testbed"
    port: 25565
    targetPort: 25565
  - name: "newhome"
    port: 25564
    targetPort: 25564
  - name: "newhome-dynmap"
    port: 8123
    targetPort: 8123
  - name: "crafty"
    port: 8000
    targetPort: 8000
  selector:
    app: minecraft-crafty
status:
  loadBalancer: {}
